# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MagentoCli < Formula
  desc "tool for managing magento and serving local versions"
  homepage "https://superterran.net/magento-cli/"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/superterran/magento-cli/releases/download/v0.1.0/magento-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "31700e8a58ae2b9f32133b43b5372d2b0d1cd8ef2a28ac38b2a2cc02594104db"

      def install
        bin.install "magento"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/superterran/magento-cli/releases/download/v0.1.0/magento-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "2b8010d6a06261b0a0f5ceed8fcb7b0697331b7f2566bcc617aebc027e87ffee"

      def install
        bin.install "magento"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/superterran/magento-cli/releases/download/v0.1.0/magento-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "d9cbfdbc9a27061394dfba4d535cb21123a13a345f2fcf51033d4ccf9b20fd00"

      def install
        bin.install "magento"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/superterran/magento-cli/releases/download/v0.1.0/magento-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "3c52af39bd3ff36590396fc2860e6e10d8e8bc82550b80411f6032411bdbe017"

      def install
        bin.install "magento"
      end
    end
  end

  depends_on "docker" => :optional
  depends_on "docker-compose" => :optional
  depends_on "git" => :optional

  def caveats; <<~EOS
    How to use this binary
  EOS
  end

  test do
    system "#{bin}/magento -h"
  end
end
