# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MagentoCli < Formula
  desc "run magento natively with dockerized backend services"
  homepage "https://magento-cli.com"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/blueacorninc/magento-cli/releases/download/v0.1.6/magento-cli_0.1.6_darwin_arm64.tar.gz"
      sha256 "35790973b8380d4016242e77b2f3ec0ab3e070854664bc875c462dcc18171e78"

      def install
        bin.install "magento"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/blueacorninc/magento-cli/releases/download/v0.1.6/magento-cli_0.1.6_darwin_amd64.tar.gz"
      sha256 "75e97493df2119e8c4d39c45f024edc3619fde3fb4aff2fcff7811f4e8d31c80"

      def install
        bin.install "magento"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/blueacorninc/magento-cli/releases/download/v0.1.6/magento-cli_0.1.6_linux_amd64.tar.gz"
      sha256 "4c8364d45672d1fad7c7082d145d401d3fefcea9884bd3671fb653a0c76ac934"

      def install
        bin.install "magento"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blueacorninc/magento-cli/releases/download/v0.1.6/magento-cli_0.1.6_linux_arm64.tar.gz"
      sha256 "0438baa3b8229eea7cf7c173c7135fb142ec967c12a30b34ecf85cc1793a3e82"

      def install
        bin.install "magento"
      end
    end
  end

  depends_on "docker" => :required
  depends_on "docker-compose" => :required
  depends_on "git" => :optional

  def caveats; <<~EOS
    How to use this binary
  EOS
  end

  test do
    system "#{bin}/magento -h"
  end
end
