# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MagentoCli < Formula
  desc "tool for managing magento and serving local versions"
  homepage "https://superterran.net/magento-cli/"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blueacorninc/magento-cli/releases/download/v0.1.4/magento-cli_0.1.4_darwin_amd64.tar.gz"
      sha256 "7bff1ec6e6956501689a197d87582695f7f1f7437cb925522ebaec7185f45f81"

      def install
        bin.install "magento"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blueacorninc/magento-cli/releases/download/v0.1.4/magento-cli_0.1.4_darwin_arm64.tar.gz"
      sha256 "0d004ae24b2c190708632784022943e8f0fa06539ded3a38f1b9a6646c0f2dac"

      def install
        bin.install "magento"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/blueacorninc/magento-cli/releases/download/v0.1.4/magento-cli_0.1.4_linux_amd64.tar.gz"
      sha256 "71a11db7f81633d8c0b6f7f0a3712cc9b9c938e227d1abe6b01fcfa11e0e829e"

      def install
        bin.install "magento"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blueacorninc/magento-cli/releases/download/v0.1.4/magento-cli_0.1.4_linux_arm64.tar.gz"
      sha256 "12e18fadda6f3389c8d468deb5152636b0cfb6ffc7943a68b0ff8d3d50d3d215"

      def install
        bin.install "magento"
      end
    end
  end

  depends_on "docker" => :optional
  depends_on "docker-compose" => :optional
  depends_on "git" => :optional

  def caveats; <<~EOS
    How to use this binary
  EOS
  end

  test do
    system "#{bin}/magento -h"
  end
end
